### ISSUE TITLE
If connection unavailable when integration starts, it fails

### ISSUE THREAD

**Issue by robin13** [legrego/homeassistant-elasticsearch#170]
**Environment**
Home-Assistant version: 2023.2.5
Elasticsearch version: 8.6.0

Relevant `configuration.yml` settings:
```json
      {
        "entry_id": "68f04bbd035ce5624f5d4e46f521e682",
        "version": 2,
        "domain": "elasticsearch",
        "title": "https://**************************.eu-central-1.aws.cloud.es.io:9243",
        "data": {
          "url": "https://**************************.eu-central-1.aws.cloud.es.io:9243",
          "username": "elastic",
          "password": "*******************",
          "timeout": 30,
          "verify_ssl": true,
          "ssl_ca_path": null,
          "publish_enabled": true,
          "publish_frequency": 60,
          "alias": "active-hass-index",
          "index_format": "hass-events",
          "excluded_domains": [],
          "excluded_entities": [],
          "health_sensor_enabled": true,
          "ilm_enabled": true,
          "ilm_policy_name": "home-assistant",
          "ilm_max_size": "5gb",
          "ilm_delete_after": "365d",
          "publish_mode": "Any changes"
        },
        "options": {
          "publish_enabled": true,
          "publish_frequency": 60,
          "only_publish_changed": true,
          "excluded_domains": [],
          "excluded_entities": [],
          "index_format": "hass-events",
          "alias": "active-hass-index",
          "ilm_enabled": true,
          "ilm_policy_name": "home-assistant",
          "ilm_max_size": "5gb",
          "ilm_delete_after": "365d",
          "health_sensor_enabled": true,
          "publish_mode": "State changes",
          "included_domains": [],
          "included_entities": []
        },
        "pref_disable_new_entities": false,
        "pref_disable_polling": false,
        "source": "user",
        "unique_id": "https://**************************.eu-central-1.aws.cloud.es.io:9243",
        "disabled_by": null
      },
```

**Describe the bug**
From the logs of the last home assistant restart it looks as if the elasticsearch cluster was not available, or could not be reached when the integration was started. The integration did not start, and did not try to re-connect; it was dead...
When I noticed it a few days later (lots of lost data), I just clicked the "reload" button on the integration, and it started and connected fine.

**To Reproduce**
Steps to reproduce the behaviour:
1. Restart home assistant while Elasticsearch cluster is unavailable
2. Elasticsearch integration does not start

**Expected behaviour**
It would be good to have some retry cycle if the integration cannot be started first time.

**Additional context**

Section of logs where it failed on home assistant restart:

```
Logger: homeassistant.config_entries
Source: custom_components/elasticsearch/es_version.py:15
Integration: Elasticsearch (documentation, issues)
First occurred: 26 February 2023 at 00:05:03 (1 occurrences)
Last logged: 26 February 2023 at 00:05:03

Error setting up entry https://**************************.eu-central-1.aws.cloud.es.io:9243 for elasticsearch
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/_async/http_aiohttp.py", line 279, in perform_request
    async with self.session.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 466, in _request
    with timer:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/elasticsearch/__init__.py", line 147, in async_setup_entry
    init = await _async_init_integration(hass, config_entry)
  File "/config/custom_components/elasticsearch/__init__.py", line 177, in _async_init_integration
    await integration.async_init()
  File "/config/custom_components/elasticsearch/es_integration.py", line 29, in async_init
    await self.gateway.async_init()
  File "/config/custom_components/elasticsearch/es_gateway.py", line 91, in async_init
    await self.es_version.async_init()
  File "/config/custom_components/elasticsearch/es_version.py", line 15, in async_init
    version = (await self._client.info())["version"]
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/_async/client/__init__.py", line 285, in info
    return await self.transport.perform_request(
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/_async/transport.py", line 330, in perform_request
    raise e
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/_async/transport.py", line 297, in perform_request
    status, headers, data = await connection.perform_request(
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/_async/http_aiohttp.py", line 312, in perform_request
    raise ConnectionTimeout("TIMEOUT", str(e), e)
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - TimeoutError()









Logger: elasticsearch
Source: /usr/local/lib/python3.10/site-packages/elasticsearch/connection/base.py:285
First occurred: 26 February 2023 at 00:05:03 (1 occurrences)
Last logged: 26 February 2023 at 00:05:03

GET https://**************************.eu-central-1.aws.cloud.es.io:9243/ [status:N/A request:30.284s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/elasticsearch/_async/http_aiohttp.py", line 279, in perform_request
    async with self.session.request(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 466, in _request
    with timer:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

**Comment by legrego** [comment]
Thanks for raising this. I've always known in the back of my head this was an issue, but I appreciate you writing this up. I think Home Assistant has a mechanism for integrations to retry their setup, so we'll have to give that a try to see if it'll meet our needs.
