### ISSUE TITLE
Unable to serialize entity attributes whose value is a `class` instance

### ISSUE THREAD

**Issue by bad5ect0r** [legrego/homeassistant-elasticsearch#179]
It seems that my events are only publishing to Elasticsearch when I restart Home Assistant. I've left the frequency as the default 60s. I've tried 15s as well but it doesn't fix it. I've only configured the integration through the Home Assistant UI - am I missing another setting that is not in the UI?

## Home assistant version

Home Assistant 2023.9.1
Supervisor 2023.08.3
Operating System 10.5
Frontend 20230908.0 - latest

## Elasticsearch version

8.9.1

## Integration version

0.5.5

### Reboot 1

```
2023-09-12 01:19:32.799 WARNING (MainThread) [elasticsearch] GET https://elastic.lan:9200/ [status:N/A request:15.335s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/elasticsearch7/_async/http_aiohttp.py", line 279, in perform_request
    async with self.session.request(
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 560, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 32] Broken pipe
2023-09-12 01:20:56.050 DEBUG (MainThread) [custom_components.elasticsearch] Collecting queued documents for publish
2023-09-12 01:21:00.015 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:21:00.020 DEBUG (SyncWorker_4) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:21:30.020 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:21:30.026 DEBUG (SyncWorker_4) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:22:00.019 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:22:00.025 DEBUG (SyncWorker_7) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:23:00.020 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:23:00.025 DEBUG (SyncWorker_4) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:23:30.021 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:23:30.027 DEBUG (SyncWorker_9) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:24:00.022 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:24:00.028 DEBUG (SyncWorker_6) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:26:13.506 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:26:13.511 DEBUG (SyncWorker_0) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:26:43.507 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:26:43.513 DEBUG (SyncWorker_5) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:27:13.509 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:27:13.516 DEBUG (SyncWorker_0) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:27:43.513 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:27:43.518 DEBUG (SyncWorker_4) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
```

### Reboot 2

```
2023-09-12 01:33:07.657 DEBUG (MainThread) [custom_components.elasticsearch] Setting up integtation
2023-09-12 01:33:10.646 DEBUG (MainThread) [custom_components.elasticsearch] Creating Elasticsearch client for https://elastic.lan:9200
2023-09-12 01:33:11.840 DEBUG (MainThread) [custom_components.elasticsearch] Gateway initialized
2023-09-12 01:33:14.347 DEBUG (MainThread) [custom_components.elasticsearch] Ensuring ILM Policy is attached to existing index
2023-09-12 01:33:14.392 INFO (MainThread) [custom_components.elasticsearch] Updating existing ILM Policy 'home-assistant'
2023-09-12 01:33:14.559 DEBUG (MainThread) [custom_components.elasticsearch] Index Manager initialized
2023-09-12 01:33:14.559 DEBUG (MainThread) [custom_components.elasticsearch] async_init: getting system info
2023-09-12 01:33:14.560 DEBUG (MainThread) [custom_components.elasticsearch] async_init: initializing static doc properties
2023-09-12 01:33:14.560 DEBUG (MainThread) [custom_components.elasticsearch] async_init: static doc properties: {'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '2023.9.1', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': xxxxx, 'lon': xxxxx}, 'host.architecture': 'aarch64', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': None}
2023-09-12 01:33:14.560 DEBUG (MainThread) [custom_components.elasticsearch] async_init: starting publish timer
2023-09-12 01:33:14.561 DEBUG (MainThread) [custom_components.elasticsearch] async_init: done
2023-09-12 01:33:14.566 DEBUG (MainThread) [custom_components.elasticsearch] Starting publish timer: executes every 60 seconds.
2023-09-12 01:33:14.574 DEBUG (MainThread) [custom_components.elasticsearch] Collecting queued documents for publish
2023-09-12 01:33:14.581 INFO (MainThread) [custom_components.elasticsearch] Publishing 45 documents to Elasticsearch
2023-09-12 01:33:16.676 DEBUG (MainThread) [custom_components.elasticsearch] Elasticsearch bulk response: (45, [])
2023-09-12 01:33:16.676 INFO (MainThread) [custom_components.elasticsearch] Publish Succeeded
2023-09-12 01:33:20.557 INFO (MainThread) [custom_components.elasticsearch.sensor] Initializing cluster health sensor
2023-09-12 01:33:20.557 INFO (MainThread) [custom_components.elasticsearch.sensor] Initializing publish queue sensor
2023-09-12 01:33:20.558 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Adding 2 devices
2023-09-12 01:33:20.559 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:33:20.571 DEBUG (SyncWorker_3) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:33:54.005 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:33:54.013 DEBUG (SyncWorker_0) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:34:16.678 DEBUG (MainThread) [custom_components.elasticsearch] Collecting queued documents for publish
2023-09-12 01:34:23.951 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:34:23.957 DEBUG (SyncWorker_14) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:34:53.956 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:34:53.962 DEBUG (SyncWorker_12) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:35:23.953 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:35:23.963 DEBUG (SyncWorker_1) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:35:53.955 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:35:53.960 DEBUG (SyncWorker_0) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:36:23.955 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:36:23.961 DEBUG (SyncWorker_9) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:36:53.958 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:36:53.963 DEBUG (SyncWorker_13) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:37:23.961 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:37:23.967 DEBUG (SyncWorker_1) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:37:53.963 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:37:53.968 DEBUG (SyncWorker_4) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:38:23.964 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:38:23.970 DEBUG (SyncWorker_5) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
2023-09-12 01:38:53.965 DEBUG (MainThread) [custom_components.elasticsearch.sensor] Updating Elasticsearch cluster health
2023-09-12 01:38:53.970 DEBUG (SyncWorker_1) [custom_components.elasticsearch.sensor] Updating Elasticsearch queue stats
```

**Comment by bad5ect0r** [comment]
Okay, I was aiming to fix this one on my own before I posted this and looks like I found the culprit by chance soon after I post it 🤦.

For background, I also run another custom integration to extract my robot vacuum cleaner's map using https://github.com/PiotrMachowski/Home-Assistant-custom-components-Xiaomi-Cloud-Map-Extractor. I ran into this stack trace which pointed to this having something to do with the issue:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/elasticsearch7/serializer.py", line 130, in dumps
    return json.dumps(
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/simplejson/__init__.py", line 395, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/simplejson/encoder.py", line 298, in encode
    chunks = self.iterencode(o)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/simplejson/encoder.py", line 379, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/elasticsearch/es_serializer.py", line 15, in default
    return JSONSerializer.default(self, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elasticsearch7/serializer.py", line 116, in default
    raise TypeError("Unable to serialize %r (type: %s)" % (data, type(data)))
TypeError: Unable to serialize [number: 16, name: None, xxx, xxx, xxx, xxx] (type: <class 'custom_components.xiaomi_cloud_map_extractor.common.map_data.Room'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/elasticsearch/__init__.py", line 166, in async_config_entry_updated
    return await _async_init_integration(hass, config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/elasticsearch/__init__.py", line 171, in _async_init_integration
    await async_unload_entry(hass, config_entry)
  File "/config/custom_components/elasticsearch/__init__.py", line 156, in async_unload_entry
    await existing_instance.async_shutdown(config_entry)
  File "/config/custom_components/elasticsearch/es_integration.py", line 54, in async_shutdown
    await self.publisher.async_stop_publisher()
  File "/config/custom_components/elasticsearch/es_doc_publisher.py", line 165, in async_stop_publisher
    await self.async_do_publish()
  File "/config/custom_components/elasticsearch/es_doc_publisher.py", line 207, in async_do_publish
    actions.append(self._state_to_bulk_action(state, event.time_fired))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/elasticsearch/es_doc_publisher.py", line 352, in _state_to_bulk_action
    self._serializer.dumps(value) if should_serialize else value
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elasticsearch7/serializer.py", line 134, in dumps
    raise SerializationError(data, e)
elasticsearch7.exceptions.SerializationError: ({16: [number: 16, name: None, xxx, xxx, xxx, xxx], 18: [number: 18, name: None, xxx, xxx, xxx, xxx], 19: [number: 19, name: None, xxx, xxx, xxx, xxx], 17: [number: 17, name: None, xxx, xxx, xxx, xxx], 1: [number: 1, name: None, xxx, xxx, xxx, xxx]}, TypeError("Unable to serialize [number: 16, name: None, xxx, xxx, xxx, xxx] (type: <class 'custom_components.xiaomi_cloud_map_extractor.common.map_data.Room'>)"))
```
I've tried to obfuscate room dimensions for privacy reasons but where there's an `xxx` there is an integer. I'm guessing the elasticsearch integration is having trouble serializing this data? I haven't looked at the code for this integration to understand how it works. I barely understand Elasticsearch 😆 .

Feel free to close it if it's not relevant.

**Comment by legrego** [comment]
Thanks for the detailed writeup and investigation. What's happening here is that we aren't accounting for the fact that an entity might have an instance of a python class as an attribute value. The logic for this is [here](https://github.com/legrego/homeassistant-elasticsearch/blob/515877df4133ac6185e8eab1be6804ec79ada12b/custom_components/elasticsearch/es_doc_publisher.py#L342-L353), but I don't know how to best resolve this, yet.

I'll leave this issue open in case others encounter it. I'm glad you found a workaround for the time being.

https://github.com/legrego/homeassistant-elasticsearch/blob/515877df4133ac6185e8eab1be6804ec79ada12b/custom_components/elasticsearch/es_doc_publisher.py#L342-L353
