### ISSUE TITLE
descriptor 'replace' for 'str' objects doesn't apply to a 'datetime.date' object

### ISSUE THREAD

**Issue by jeanfabrice** [legrego/homeassistant-elasticsearch#192]
**Environment**
Home-Assistant version: 2023.11.2
Elasticsearch version: 8.11.1

**Describe the bug**
A particular HASS entity is throwing the following error: 
```
2023-11-20 22:03:05.262 ERROR (MainThread) [custom_components.elasticsearch] Error during publish queue handling descriptor 'replace' for 'str' objects doesn't apply to a 'datetime.date' object
Traceback (most recent call last):
  File "/config/custom_components/elasticsearch/es_doc_publisher.py", line 456, in _publish_queue_timer
    await self.async_do_publish()
  File "/config/custom_components/elasticsearch/es_doc_publisher.py", line 237, in async_do_publish
    self._state_to_bulk_action(state, self._last_publish_time)
  File "/config/custom_components/elasticsearch/es_doc_publisher.py", line 329, in _state_to_bulk_action
    key = str.replace(orig_key, ".", "_")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: descriptor 'replace' for 'str' objects doesn't apply to a 'datetime.date' object
```
blocking the entire ingestion

**Additional context**
This entity is a sort of hash indexed by date.
It has been introduced recently as part of another HACS plugin I'm using.
The detail for this entity is here: 
https://github.com/Hyundai-Kia-Connect/kia_uvo/pull/753/files#diff-423db82c1b9f546ecfbe55072f70d2c15213e34224c4f00cc1f4976215808903R307-R344

I understand the key of the hash is a date (`key = day.date.date()`) for which `str.replace` is not a supported method.
I don't know whether you should cast `orig_key` to string before applying `str.replace` or if the author of the other HACS plugin should not use a date object as a key...

As a temporary fix, I excluded this entity from being indexed.
Maybe a catch exception would be enough not to break the entire ingestion when such things happen?

**Comment by jeanfabrice** [comment]
Awesome! Thank you sooo much @legrego!!
