### ISSUE TITLE
Unauthenticated Elasticsearch does not work

### ISSUE THREAD

**Issue by strawgate** [legrego/homeassistant-elasticsearch#241]
When setting up Elasticsearch in unauthenticated mode it still performs a privileges check which fails when security is disabled.

```
2024-03-27 18:13:24.773 DEBUG (MainThread) [custom_components.elasticsearch] Creating Elasticsearch client for http://localhost:9200
2024-03-27 18:13:24.786 INFO (MainThread) [elasticsearch] GET http://localhost:9200/ [status:200 request:0.012s]
2024-03-27 18:13:24.786 DEBUG (MainThread) [custom_components.elasticsearch] Gateway initialized
2024-03-27 18:13:24.786 DEBUG (MainThread) [custom_components.elasticsearch] Starting privilege enforcement
2024-03-27 18:13:24.786 DEBUG (MainThread) [custom_components.elasticsearch] Privilege check starting
2024-03-27 18:13:24.795 WARNING (MainThread) [elasticsearch] POST http://localhost:9200/_security/user/_has_privileges [status:500 request:0.008s]
2024-03-27 18:13:24.795 ERROR (MainThread) [custom_components.elasticsearch] Error performing privilege check: TransportError(500, 'exception', 'Security must be explicitly enabled when using a [basic] license. Enable security by setting [xpack.security.enabled] to [true] in the elasticsearch.yml file and restart the node.')
Traceback (most recent call last):
  File "/workspaces/homeassistant-elasticsearch/custom_components/elasticsearch/es_privilege_check.py", line 68, in check_privileges
    privilege_response =  await es_client.security.has_privileges(body={
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/homeassistant-elasticsearch/.venv/lib/python3.11/site-packages/elasticsearch7/_async/client/security.py", line 385, in has_privileges
    return await self.transport.perform_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/homeassistant-elasticsearch/.venv/lib/python3.11/site-packages/elasticsearch7/_async/transport.py", line 330, in perform_request
    raise e
  File "/workspaces/homeassistant-elasticsearch/.venv/lib/python3.11/site-packages/elasticsearch7/_async/transport.py", line 297, in perform_request
    status, headers, data = await connection.perform_request(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/homeassistant-elasticsearch/.venv/lib/python3.11/site-packages/elasticsearch7/_async/http_aiohttp.py", line 330, in perform_request
    self._raise_error(response.status, raw_data)
  File "/workspaces/homeassistant-elasticsearch/.venv/lib/python3.11/site-packages/elasticsearch7/connection/base.py", line 322, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(
elasticsearch7.exceptions.TransportError: TransportError(500, 'exception', 'Security must be explicitly enabled when using a [basic] license. Enable security by setting [xpack.security.enabled] to [true] in the elasticsearch.yml file and restart the node.')
2024-03-27 18:13:24.797 ERROR (MainThread) [custom_components.elasticsearch] Unknown error connecting with Elasticsearch cluster. ('Error performing privilege check', TransportError(500, 'exception', {'error': {'root_cause': [{'type': 'exception', 'reason': 'Security must be explicitly enabled when using a [basic] license. Enable security by setting [xpack.security.enabled] to [true] in the elasticsearch.yml file and restart the node.'}], 'type': 'exception', 'reason': 'Security must be explicitly enabled when using a [basic] license. Enable security by setting [xpack.security.enabled] to [true] in the elasticsearch.yml file and restart the node.'}, 'status': 500}))
```

**Comment by legrego** [comment]
Good catch, thanks for opening this. I assume this is a regression introduced in [`v0.6.1`](https://github.com/legrego/homeassistant-elasticsearch/releases/tag/v0.6.1) via https://github.com/legrego/homeassistant-elasticsearch/pull/189
