### ISSUE TITLE
Elasticsearch integration not loading after most recent HA update

### ISSUE THREAD

**Issue by mike12806** [legrego/homeassistant-elasticsearch#398]
**Environment**
Home-Assistant version: 2024.12.0
Elasticsearch version: x.y.z

Relevant `configuration.yml` settings:
```yml
# Do not include your Elasticsearch URL, credentials, or any other sensitive information
elastic:
  ...
```

**Describe the bug**

**To Reproduce**

logger:%20homeassistant.setup%0ASource%3A%20setup.py%3A334%0AFirst%20occurred%3A%2011%3A58%3A39%20PM%20(1%20occurrences)%0ALast%20logged%3A%2011%3A58%3A39%20PM%0A%0ASetup%20failed%20for%20custom%20integration%20'elasticsearch'%3A%20Unable%20to%20import%20component%3A%20Exception%20importing%20custom_components.elasticsearch%0ATraceback%20(most%20recent%20call%20last)%3A%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/loader.py%22,%20line%201074,%20in%20_get_component%0A%20%20%20%20ComponentProtocol,%20importlib.import_module(self.pkg_path)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20~~~~~~~~~~~~~~~~~~~~~~~%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/util/loop.py%22,%20line%20200,%20in%20protected_loop_func%0A%20%20%20%20return%20func(*args,%20**kwargs)%0A%20%20File%20%22/usr/local/lib/python3.13/importlib/__init__.py%22,%20line%2088,%20in%20import_module%0A%20%20%20%20return%20_bootstrap._gcd_import(name%5Blevel:%5D,%20package,%20level)%0A%20%20%20%20%20%20%20%20%20%20%20~~~~~~~~~~~~~~~~~~~~~~%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22%3Cfrozen%20importlib._bootstrap%3E%22,%20line%201387,%20in%20_gcd_import%0A%20%20File%20%22%3Cfrozen%20importlib._bootstrap%3E%22,%20line%201360,%20in%20_find_and_load%0A%20%20File%20%22%3Cfrozen%20importlib._bootstrap%3E%22,%20line%201331,%20in%20_find_and_load_unlocked%0A%20%20File%20%22%3Cfrozen%20importlib._bootstrap%3E%22,%20line%20935,%20in%20_load_unlocked%0A%20%20File%20%22%3Cfrozen%20importlib._bootstrap_external%3E%22,%20line%201022,%20in%20exec_module%0A%20%20File%20%22%3Cfrozen%20importlib._bootstrap%3E%22,%20line%20488,%20in%20_call_with_frames_removed%0A%20%20File%20%22/config/custom_components/elasticsearch/__init__.py%22,%20line%2043,%20in%20%3Cmodule%3E%0A%20%20%20%20from%20.es_integration%20import%20ElasticIntegration%0A%20%20File%20%22/config/custom_components/elasticsearch/es_integration.py%22,%20line%2011,%20in%20%3Cmodule%3E%0A%20%20%20%20from%20.es_doc_publisher%20import%20DocumentPublisher%0A%20%20File%20%22/config/custom_components/elasticsearch/es_doc_publisher.py%22,%20line%2015,%20in%20%3Cmodule%3E%0A%20%20%20%20from%20custom_components.elasticsearch.es_index_manager%20import%20IndexManager%0A%20%20File%20%22/config/custom_components/elasticsearch/es_index_manager.py%22,%20line%206,%20in%20%3Cmodule%3E%0A%20%20%20%20from%20elasticsearch7%20import%20ElasticsearchException%0A%20%20File%20%22/usr/local/lib/python3.13/site-packages/elasticsearch7/__init__.py%22,%20line%2036,%20in%20%3Cmodule%3E%0A%20%20%20%20from%20.client%20import%20Elasticsearch%0A%20%20File%20%22/usr/local/lib/python3.13/site-packages/elasticsearch7/client/__init__.py%22,%20line%2022,%20in%20%3Cmodule%3E%0A%20%20%20%20from%20..transport%20import%20Transport,%20TransportError%0A%20%20File%20%22/usr/local/lib/python3.13/site-packages/elasticsearch7/transport.py%22,%20line%2025,%20in%20%3Cmodule%3E%0A%20%20%20%20from%20.serializer%20import%20JSONSerializer,%20Deserializer,%20DEFAULT_SERIALIZERS%0A%20%20File%20%22/usr/local/lib/python3.13/site-packages/elasticsearch7/serializer.py%22,%20line%2050,%20in%20%3Cmodule%3E%0A%20%20%20%20np.float_,%0A%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.13/site-packages/numpy/__init__.py%22,%20line%20400,%20in%20__getattr__%0A%20%20%20%20raise%20AttributeError(%0A%20%20%20%20...%3C3%20lines%3E...%0A%20%20%20%20)%0AAttributeError:%20%60np.float_%60%20was%20removed%20in%20the%20NumPy%202.0%20release.%20Use%20%60np.float64%60%20instead.%0A%0AThe%20above%20exception%20was%20the%20direct%20cause%20of%20the%20following%20exception:%0A%0ATraceback%20(most%20recent%20call%20last):%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/loader.py%22,%20line%201014,%20in%20async_get_component%0A%20%20%20%20comp%20=%20await%20self.hass.async_add_import_executor_job(%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20%20%20%20%20%20%20self._get_component,%20True%0A%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20%20%20)%0A%20%20%20%20%5E%0A%20%20File%20%22/usr/local/lib/python3.13/concurrent/futures/thread.py%22,%20line%2058,%20in%20run%0A%20%20%20%20result%20=%20self.fn(*self.args,%20**self.kwargs)%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/loader.py%22,%20line%201085,%20in%20_get_component%0A%20%20%20%20raise%20ImportError(f%22Exception%20importing%20%7Bself.pkg_path%7D%22)%20from%20err%0AImportError:%20Exception%20importing%20custom_components.elasticsearch%0A%0ADuring%20handling%20of%20the%20above%20exception,%20another%20exception%20occurred:%0A%0ATraceback%20(most%20recent%20call%20last):%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/loader.py%22,%20line%201074,%20in%20_get_component%0A%20%20%20%20ComponentProtocol,%20importlib.import_module(self.pkg_path)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20~~~~~~~~~~~~~~~~~~~~~~~%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/util/loop.py%22,%20line%20200,%20in%20protected_loop_func%0A%20%20%20%20return%20func(*args,%20**kwargs)%0A%20%20File%20%22/usr/local/lib/python3.13/importlib/__init__.py%22,%20line%2088,%20in%20import_module%0A%20%20%20%20return%20_bootstrap._gcd_import(name%5Blevel:%5D,%20package,%20level)%0A%20%20%20%20%20%20%20%20%20%20%20~~~~~~~~~~~~~~~~~~~~~~%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22%3Cfrozen%20importlib._bootstrap%3E%22,%20line%201387,%20in%20_gcd_import%0A%20%20File%20%22%3Cfrozen%20importlib._bootstrap%3E%22,%20line%201360,%20in%20_find_and_load%0A%20%20File%20%22%3Cfrozen%20importlib._bootstrap%3E%22,%20line%201331,%20in%20_find_and_load_unlocked%0A%20%20File%20%22%3Cfrozen%20importlib._bootstrap%3E%22,%20line%20935,%20in%20_load_unlocked%0A%20%20File%20%22%3Cfrozen%20importlib._bootstrap_external%3E%22,%20line%201022,%20in%20exec_module%0A%20%20File%20%22%3Cfrozen%20importlib._bootstrap%3E%22,%20line%20488,%20in%20_call_with_frames_removed%0A%20%20File%20%22/config/custom_components/elasticsearch/__init__.py%22,%20line%2043,%20in%20%3Cmodule%3E%0A%20%20%20%20from%20.es_integration%20import%20ElasticIntegration%0A%20%20File%20%22/config/custom_components/elasticsearch/es_integration.py%22,%20line%2011,%20in%20%3Cmodule%3E%0A%20%20%20%20from%20.es_doc_publisher%20import%20DocumentPublisher%0A%20%20File%20%22/config/custom_components/elasticsearch/es_doc_publisher.py%22,%20line%2015,%20in%20%3Cmodule%3E%0A%20%20%20%20from%20custom_components.elasticsearch.es_index_manager%20import%20IndexManager%0A%20%20File%20%22/config/custom_components/elasticsearch/es_index_manager.py%22,%20line%206,%20in%20%3Cmodule%3E%0A%20%20%20%20from%20elasticsearch7%20import%20ElasticsearchException%0A%20%20File%20%22/usr/local/lib/python3.13/site-packages/elasticsearch7/__init__.py%22,%20line%2036,%20in%20%3Cmodule%3E%0A%20%20%20%20from%20.client%20import%20Elasticsearch%0A%20%20File%20%22/usr/local/lib/python3.13/site-packages/elasticsearch7/client/__init__.py%22,%20line%2022,%20in%20%3Cmodule%3E%0A%20%20%20%20from%20..transport%20import%20Transport,%20TransportError%0A%20%20File%20%22/usr/local/lib/python3.13/site-packages/elasticsearch7/transport.py%22,%20line%2025,%20in%20%3Cmodule%3E%0A%20%20%20%20from%20.serializer%20import%20JSONSerializer,%20Deserializer,%20DEFAULT_SERIALIZERS%0A%20%20File%20%22/usr/local/lib/python3.13/site-packages/elasticsearch7/serializer.py%22,%20line%2050,%20in%20%3Cmodule%3E%0A%20%20%20%20np.float_,%0A%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.13/site-packages/numpy/__init__.py%22,%20line%20400,%20in%20__getattr__%0A%20%20%20%20raise%20AttributeError(%0A%20%20%20%20...%3C3%20lines%3E...%0A%20%20%20%20)%0AAttributeError:%20%60np.float_%60%20was%20removed%20in%20the%20NumPy%202.0%20release.%20Use%20%60np.float64%60%20instead.%0A%0AThe%20above%20exception%20was%20the%20direct%20cause%20of%20the%20following%20exception:%0A%0ATraceback%20(most%20recent%20call%20last):%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/setup.py%22,%20line%20334,%20in%20_async_setup_component%0A%20%20%20%20component%20=%20await%20integration.async_get_component()%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/loader.py%22,%20line%201034,%20in%20async_get_component%0A%20%20%20%20self._component_future.result()%0A%20%20%20%20~~~~~~~~~~~~~~~~~~~~~~~~~~~~~%5E%5E%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/loader.py%22,%20line%201026,%20in%20async_get_component%0A%20%20%20%20comp%20=%20self._get_component()%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/loader.py%22,%20line%201085,%20in%20_get_component%0A%20%20%20%20raise%20ImportError(f%22Exception%20importing%20%7Bself.pkg_path%7D%22)%20from%20err%0AImportError:%20Exception%20importing%20custom_components.elasticsearch%0A

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by legrego** [comment]
Thanks for raising this, @mike12806. It looks like there is an incompatibility with the bersion of the ES Client we're using in the `0.7.x` line of this component.

@sorenlouv discovered that updating to version 2 of our component fixes the issue, but there are significant changes between `0.7` and `2.0`.

https://github.com/legrego/homeassistant-elasticsearch/releases/tag/v2.0.0-RC2

**Comment by dwissm1** [comment]
I jumped up to 2.0 after .7 went haywire and no matter what I do I cannot disable Verify TLS certificate (recommended) and Verify hostname matches server certificate.  It forces me to enable them but I'm running on a local network and don't care about it.  Just want the logs. 

Any ideas?

**Comment by mike12806** [comment]
> Thanks for raising this, @mike12806. It looks like there is an incompatibility with the bersion of the ES Client we're using in the `0.7.x` line of this component.
> 
> @sorenlouv discovered that updating to version 2 of our component fixes the issue, but there are significant changes between `0.7` and `2.0`.
> 
> https://github.com/legrego/homeassistant-elasticsearch/releases/tag/v2.0.0-RC2

What type of significant changes? I'm using a pretty bog standard Elasticsearch setup and trying to connect without auth over http.... 

This is with v2.0.0-RC3

```
2024-12-06 00:05:40.091 INFO (MainThread) [custom_components.elasticsearch] Entering custom_components.elasticsearch.config_flow : ElasticFlowHandler.async_step_user
2024-12-06 00:05:40.091 INFO (MainThread) [custom_components.elasticsearch] Returning from custom_components.elasticsearch.config_flow : ElasticFlowHandler.async_step_user
2024-12-06 00:05:59.164 INFO (MainThread) [custom_components.elasticsearch] Entering custom_components.elasticsearch.config_flow : ElasticFlowHandler.async_step_user
2024-12-06 00:05:59.165 INFO (MainThread) [custom_components.elasticsearch] Returning from custom_components.elasticsearch.config_flow : ElasticFlowHandler.async_step_user
2024-12-06 00:05:59.177 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/config/custom_components/elasticsearch/es_gateway_8.py", line 302, in _error_converter
    yield
  File "/config/custom_components/elasticsearch/es_gateway_8.py", line 196, in has_privileges
    response = await self.client.security.has_privileges(**privileges)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/elasticsearch8/_async/client/security.py", line 1811, in has_privileges
    return await self.perform_request(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
```

**Comment by strawgate** [comment]
The 2.0 integration switches to using data streams by default and changes the schema and mapping to take full advantage of data types in Elasticsearch (among other things).

You will have to update the permissions for your home assistant use following the setup instructions in the wiki.

You'll also have to update visualizations to use the new mappings.

**Comment by strawgate** [comment]
> I jumped up to 2.0 after .7 went haywire and no matter what I do I cannot disable Verify TLS certificate (recommended) and Verify hostname matches server certificate.  It forces me to enable them but I'm running on a local network and don't care about it.  Just want the logs. 
> 
> Any ideas?
> 
> Usually in the code I do:
> 
> verify_certs=False,
> ssl_show_warn=False,
> 

Can you file a separate issue with this? Can you include debug logs of you attempting to set this up?

**Comment by mike12806** [comment]
> > I jumped up to 2.0 after .7 went haywire and no matter what I do I cannot disable Verify TLS certificate (recommended) and Verify hostname matches server certificate.  It forces me to enable them but I'm running on a local network and don't care about it.  Just want the logs.
> > Any ideas?
> > Usually in the code I do:
> > verify_certs=False,
> > ssl_show_warn=False,
> 
> Can you file a separate issue with this? Can you include debug logs of you attempting to set this up?

I’m hitting the same issue. Will open another issue

**Comment by mike12806** [comment]
https://github.com/legrego/homeassistant-elasticsearch/issues/399

**Comment by strawgate** [comment]
Looks like fixing this on the 0.7.x branch would require bumping the ES7 dependency to 7.17.12 https://github.com/elastic/elasticsearch-py/releases/tag/v7.17.12

That may break compatibility with 7.11 to 7.16.

As an alternative we could bump the 1.x branch to minimum 7.16 and then release the 1.x branch

**Comment by bdauvissat** [comment]
Since my last update of HA, I have quite a similar error, the logs are a little bit different.
![image](https://github.com/user-attachments/assets/7ed5110a-e3b9-476b-981f-18cd7a2670a2)
My current version : 
![image](https://github.com/user-attachments/assets/debbdea9-17a6-46e6-80ea-95f4aae54c4a)

**Comment by strawgate** [comment]
> Since my last update of HA, I have quite a similar error, the logs are a little bit different.
> ![image](https://github.com/user-attachments/assets/7ed5110a-e3b9-476b-981f-18cd7a2670a2)
> My current version : 
> ![image](https://github.com/user-attachments/assets/debbdea9-17a6-46e6-80ea-95f4aae54c4a)
> 
> I also tried to remove the integration (successfully) and add it again and then, I have an error message
> 

Hi, 

Can you file a new issue with your information? Can you include the version of the integration as well as the full text from the exception on line one?

**Comment by strawgate** [comment]
Hi, we have published a new pre-release of the v1.0.0 branch that should resolve this issue. Can you switch to that version? For others watching this issue, please note the minimum Elasticsearch version has changed to 7.17 for the v1.0.0 branch.

**Comment by mike12806** [comment]
> Hi, we have published a new pre-release of the v1.0.0 branch that should resolve this issue. Can you switch to that version? For others watching this issue, please note the minimum Elasticsearch version has changed to 7.17 for the v1.0.0 branch.

Sure - I have things working now on v2.0.0-RC4 but I can try to swap back and see if things work on the new v1 branch in a bit

**Comment by strawgate** [comment]
Staying on the 2.0.0 branch is fine too :) Swapping back while pointed to the same destination ES cluster may complicate things
