### ISSUE TITLE
[2.0] Undetermined issue serializing the area of a device

### ISSUE THREAD

**Issue by strawgate** [legrego/homeassistant-elasticsearch#414]
Background info, area is not set on the entity, but is set on the device. I did not notice anything weird on the area's definition.

```
024-12-19 18:16:06.075 ERROR (MainThread) [custom_components.elasticsearch-https1921680449200] Error formatting document for entity [sensor.shelly9_proxmox1_switch_0_energy]. Skipping document.
Traceback (most recent call last):
  File "/config/custom_components/elasticsearch/es_publish_pipeline.py", line 261, in _sip_queue
    yield self._formatter.format(timestamp, state, reason)
          ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/elasticsearch/es_publish_pipeline.py", line 585, in format
    **self._state_to_extended_details(state),
      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/config/custom_components/elasticsearch/es_publish_pipeline.py", line 601, in _state_to_extended_details
    entry_dict = extended_registry_entry.to_dict(flatten=True, keep_keys=KEYS_TO_KEEP)
  File "/config/custom_components/elasticsearch/entity_details.py", line 175, in to_dict
    as_dict["area"] = asdict(self.area)
                      ~~~~~~^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dataclasses.py", line 1359, in asdict
    return _asdict_inner(obj, dict_factory)
  File "/usr/local/lib/python3.13/dataclasses.py", line 1370, in _asdict_inner
    f.name: _asdict_inner(getattr(obj, f.name), dict)
            ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dataclasses.py", line 1383, in _asdict_inner
    _asdict_inner(k, dict_factory): _asdict_inner(v, dict_factory)
                                    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/dataclasses.py", line 1427, in _asdict_inner
    return copy.deepcopy(obj)
           ~~~~~~~~~~~~~^^^^^
  File "/usr/local/lib/python3.13/copy.py", line 152, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'orjson.Fragment' object
```

**Comment by strawgate** [comment]
Seems related to https://github.com/legrego/homeassistant-elasticsearch/issues/402
