### ISSUE TITLE
Hass domain ZONE

### ISSUE THREAD

**Issue by tjorim** [legrego/homeassistant-elasticsearch#60]
**Environment**
Home-Assistant version: 0.90.2
Elasticsearch version: 7.0.0-rc1

Relevant `configuration.yml` settings:
```yml
elastic:
    url: http://192.168.1.187:9200
```

**Describe the bug**
Various errors in the HA log about zones.

mapper_parsing_exception, failed to parse field [hass.value] of type [long] in document with id 'gHZGyWkBVxYPvKEP6fdQ' caused_by illegal_argument_exception, For input string: "zoning".

```
Error publishing documents to Elasticsearch: ('5 document(s) failed to index.', [{'index': {'_index': 'hass-events-v2-000001', '_type': 'doc', '_id': 'gHZGyWkBVxYPvKEP6fdQ', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [hass.value] of type [long] in document with id 'gHZGyWkBVxYPvKEP6fdQ'", 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'For input string: "zoning"'}}, 'data': {'hass.domain': 'zone', 'hass.object_id': 'home', 'hass.entity_id': 'zone.home', 'hass.attributes': {'hidden': True, 'latitude': 50.8823, 'longitude': 4.7028, 'radius': 100, 'friendly_name': 'Statik', 'icon': 'mdi:home'}, 'hass.value': 'zoning', '@timestamp': datetime.datetime(2019, 3, 29, 12, 47, 40, 729443), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.90.2', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 50.8823, 'lon': 4.7028}, 'host.architecture': 'armv7l', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass'], 'hass.geo.location': {'lat': 50.8823, 'lon': 4.7028}}}}, {'index': {'_index': 'hass-events-v2-000001', '_type': 'doc', '_id': 'gnZGyWkBVxYPvKEP6fdQ', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [hass.value] of type [long] in document with id 'gnZGyWkBVxYPvKEP6fdQ'", 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'For input string: "sunny"'}}, 'data': {'hass.domain': 'weather', 'hass.object_id': 'leuven', 'hass.entity_id': 'weather.leuven', 'hass.attributes': {'temperature': 15.4, 'humidity': 52, 'pressure': 1030.2, 'wind_bearing': 75, 'wind_speed': 1.8, 'visibility': 21100, 'attribution': 'Data provided by buienradar.nl', 'forecast': [{'datetime': datetime.datetime(2019, 3, 30, 12, 0, tzinfo=<DstTzInfo 'Europe/Amsterdam' CET+1:00:00 STD>), 'condition': 'partlycloudy', 'templow': 5.0, 'temperature': 18.0}, {'datetime': datetime.datetime(2019, 3, 31, 12, 0, tzinfo=<DstTzInfo 'Europe/Amsterdam' CET+1:00:00 STD>), 'condition': 'partlycloudy', 'templow': 5.0, 'temperature': 9.0}, {'datetime': datetime.datetime(2019, 4, 1, 12, 0, tzinfo=<DstTzInfo 'Europe/Amsterdam' CET+1:00:00 STD>), 'condition': 'partlycloudy', 'templow': -1.0, 'temperature': 10.0}, {'datetime': datetime.datetime(2019, 4, 2, 12, 0, tzinfo=<DstTzInfo 'Europe/Amsterdam' CET+1:00:00 STD>), 'condition': 'pouring', 'templow': 1.0, 'temperature': 9.0}, {'datetime': datetime.datetime(2019, 4, 3, 12, 0, tzinfo=<DstTzInfo 'Europe/Amsterdam' CET+1:00:00 STD>), 'condition': 'rainy', 'templow': 2.0, 'temperature': 7.0}], 'friendly_name': 'Leuven'}, 'hass.value': 'sunny', '@timestamp': datetime.datetime(2019, 3, 29, 12, 47, 40, 729443), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.90.2', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 50.8823, 'lon': 4.7028}, 'host.architecture': 'armv7l', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}, {'index': {'_index': 'hass-events-v2-000001', '_type': 'doc', '_id': 'hnZGyWkBVxYPvKEP6fdQ', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [hass.value] of type [long] in document with id 'hnZGyWkBVxYPvKEP6fdQ'", 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'For input string: "paused"'}}, 'data': {'hass.domain': 'media_player', 'hass.object_id': 'octopus', 'hass.entity_id': 'media_player.octopus', 'hass.attributes': {'volume_level': 0.14, 'is_volume_muted': False, 'media_content_type': 'music', 'media_duration': 0, 'media_position': 0, 'media_position_updated_at': datetime.datetime(2019, 3, 29, 11, 17, 34, 376826, tzinfo=<UTC>), 'media_title': '', 'media_artist': '', 'media_album_name': '', 'source_list': ['C-Dance', 'dorst', 'dorst.m4a', 'FM Brussel', 'Gozadera Fm', 'RGR FM 106.5 (Electronic and Dance)', 'RTBF Pure FM 88.8 (Top-40-Pop)', 'VRT Radio 1', 'VRT Studio Brussel', 'Where Does The Good Go'], 'shuffle': False, 'sonos_group': ['media_player.octopus'], 'friendly_name': 'Octopus', 'supported_features': 64063}, 'hass.value': 'paused', '@timestamp': datetime.datetime(2019, 3, 29, 12, 47, 40, 729443), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.90.2', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 50.8823, 'lon': 4.7028}, 'host.architecture': 'armv7l', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}, {'index': {'_index': 'hass-events-v2-000001', '_type': 'doc', '_id': 'h3ZGyWkBVxYPvKEP6fdQ', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [hass.value] of type [long] in document with id 'h3ZGyWkBVxYPvKEP6fdQ'", 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'For input string: "paused"'}}, 'data': {'hass.domain': 'media_player', 'hass.object_id': 'rokkie_rollie', 'hass.entity_id': 'media_player.rokkie_rollie', 'hass.attributes': {'volume_level': 0.52, 'is_volume_muted': False, 'media_content_type': 'music', 'media_duration': 71, 'media_position': 0, 'media_position_updated_at': datetime.datetime(2019, 3, 29, 11, 17, 34, 502238, tzinfo=<UTC>), 'media_title': 'Happy Birthday to You - Piano Version', 'media_artist': 'Happy Birthday', 'media_album_name': 'Happy Birthday to You', 'source_list': ['C-Dance', 'dorst', 'dorst.m4a', 'FM Brussel', 'Gozadera Fm', 'RGR FM 106.5 (Electronic and Dance)', 'RTBF Pure FM 88.8 (Top-40-Pop)', 'VRT Radio 1', 'VRT Studio Brussel', 'Where Does The Good Go'], 'shuffle': False, 'sonos_group': ['media_player.rokkie_rollie'], 'friendly_name': 'Rokkie&Rollie', 'entity_picture': '/api/media_player_proxy/media_player.rokkie_rollie?token=8a7ae8a81b0889a2833cfeeca63dd98210dbcebae9f3a728b1e3d9dbeb20d40b&cache=355c957f9c61d46b', 'supported_features': 64063}, 'hass.value': 'paused', '@timestamp': datetime.datetime(2019, 3, 29, 12, 47, 40, 729443), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.90.2', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 50.8823, 'lon': 4.7028}, 'host.architecture': 'armv7l', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}, {'index': {'_index': 'hass-events-v2-000001', '_type': 'doc', '_id': 'iXZGyWkBVxYPvKEP6fdQ', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [hass.value] of type [long] in document with id 'iXZGyWkBVxYPvKEP6fdQ'", 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'For input string: "yellow"'}}, 'data': {'hass.domain': 'sensor', 'hass.object_id': 'es_cluster_health', 'hass.entity_id': 'sensor.es_cluster_health', 'hass.attributes': {'cluster_name': 'docker-cluster', 'status': 'yellow', 'timed_out': False, 'number_of_nodes': 1, 'number_of_data_nodes': 1, 'active_primary_shards': 4, 'active_shards': 4, 'relocating_shards': 0, 'initializing_shards': 0, 'unassigned_shards': 2, 'delayed_unassigned_shards': 0, 'number_of_pending_tasks': 0, 'number_of_in_flight_fetch': 0, 'task_max_waiting_in_queue_millis': 0, 'active_shards_percent_as_number': 66.66666666666666}, 'hass.value': 'yellow', '@timestamp': datetime.datetime(2019, 3, 29, 12, 47, 40, 729443), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.90.2', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 50.8823, 'lon': 4.7028}, 'host.architecture': 'armv7l', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}])
Traceback (most recent call last):
  File "/config/custom_components/elastic/__init__.py", line 309, in do_publish
    bulk_response = bulk(self._gateway.get_client(), actions)
  File "/config/deps/lib/python3.7/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "/config/deps/lib/python3.7/site-packages/elasticsearch/helpers/__init__.py", line 192, in streaming_bulk
    raise_on_error, *args, **kwargs)
  File "/config/deps/lib/python3.7/site-packages/elasticsearch/helpers/__init__.py", line 137, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
elasticsearch.helpers.BulkIndexError: ('5 document(s) failed to index.', [{'index': {'_index': 'hass-events-v2-000001', '_type': 'doc', '_id': 'gHZGyWkBVxYPvKEP6fdQ', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [hass.value] of type [long] in document with id 'gHZGyWkBVxYPvKEP6fdQ'", 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'For input string: "zoning"'}}, 'data': {'hass.domain': 'zone', 'hass.object_id': 'home', 'hass.entity_id': 'zone.home', 'hass.attributes': {'hidden': True, 'latitude': 50.8823, 'longitude': 4.7028, 'radius': 100, 'friendly_name': 'Statik', 'icon': 'mdi:home'}, 'hass.value': 'zoning', '@timestamp': datetime.datetime(2019, 3, 29, 12, 47, 40, 729443), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.90.2', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 50.8823, 'lon': 4.7028}, 'host.architecture': 'armv7l', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass'], 'hass.geo.location': {'lat': 50.8823, 'lon': 4.7028}}}}, {'index': {'_index': 'hass-events-v2-000001', '_type': 'doc', '_id': 'gnZGyWkBVxYPvKEP6fdQ', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [hass.value] of type [long] in document with id 'gnZGyWkBVxYPvKEP6fdQ'", 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'For input string: "sunny"'}}, 'data': {'hass.domain': 'weather', 'hass.object_id': 'leuven', 'hass.entity_id': 'weather.leuven', 'hass.attributes': {'temperature': 15.4, 'humidity': 52, 'pressure': 1030.2, 'wind_bearing': 75, 'wind_speed': 1.8, 'visibility': 21100, 'attribution': 'Data provided by buienradar.nl', 'forecast': [{'datetime': datetime.datetime(2019, 3, 30, 12, 0, tzinfo=<DstTzInfo 'Europe/Amsterdam' CET+1:00:00 STD>), 'condition': 'partlycloudy', 'templow': 5.0, 'temperature': 18.0}, {'datetime': datetime.datetime(2019, 3, 31, 12, 0, tzinfo=<DstTzInfo 'Europe/Amsterdam' CET+1:00:00 STD>), 'condition': 'partlycloudy', 'templow': 5.0, 'temperature': 9.0}, {'datetime': datetime.datetime(2019, 4, 1, 12, 0, tzinfo=<DstTzInfo 'Europe/Amsterdam' CET+1:00:00 STD>), 'condition': 'partlycloudy', 'templow': -1.0, 'temperature': 10.0}, {'datetime': datetime.datetime(2019, 4, 2, 12, 0, tzinfo=<DstTzInfo 'Europe/Amsterdam' CET+1:00:00 STD>), 'condition': 'pouring', 'templow': 1.0, 'temperature': 9.0}, {'datetime': datetime.datetime(2019, 4, 3, 12, 0, tzinfo=<DstTzInfo 'Europe/Amsterdam' CET+1:00:00 STD>), 'condition': 'rainy', 'templow': 2.0, 'temperature': 7.0}], 'friendly_name': 'Leuven'}, 'hass.value': 'sunny', '@timestamp': datetime.datetime(2019, 3, 29, 12, 47, 40, 729443), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.90.2', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 50.8823, 'lon': 4.7028}, 'host.architecture': 'armv7l', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}, {'index': {'_index': 'hass-events-v2-000001', '_type': 'doc', '_id': 'hnZGyWkBVxYPvKEP6fdQ', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [hass.value] of type [long] in document with id 'hnZGyWkBVxYPvKEP6fdQ'", 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'For input string: "paused"'}}, 'data': {'hass.domain': 'media_player', 'hass.object_id': 'octopus', 'hass.entity_id': 'media_player.octopus', 'hass.attributes': {'volume_level': 0.14, 'is_volume_muted': False, 'media_content_type': 'music', 'media_duration': 0, 'media_position': 0, 'media_position_updated_at': datetime.datetime(2019, 3, 29, 11, 17, 34, 376826, tzinfo=<UTC>), 'media_title': '', 'media_artist': '', 'media_album_name': '', 'source_list': ['C-Dance', 'dorst', 'dorst.m4a', 'FM Brussel', 'Gozadera Fm', 'RGR FM 106.5 (Electronic and Dance)', 'RTBF Pure FM 88.8 (Top-40-Pop)', 'VRT Radio 1', 'VRT Studio Brussel', 'Where Does The Good Go'], 'shuffle': False, 'sonos_group': ['media_player.octopus'], 'friendly_name': 'Octopus', 'supported_features': 64063}, 'hass.value': 'paused', '@timestamp': datetime.datetime(2019, 3, 29, 12, 47, 40, 729443), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.90.2', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 50.8823, 'lon': 4.7028}, 'host.architecture': 'armv7l', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}, {'index': {'_index': 'hass-events-v2-000001', '_type': 'doc', '_id': 'h3ZGyWkBVxYPvKEP6fdQ', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [hass.value] of type [long] in document with id 'h3ZGyWkBVxYPvKEP6fdQ'", 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'For input string: "paused"'}}, 'data': {'hass.domain': 'media_player', 'hass.object_id': 'rokkie_rollie', 'hass.entity_id': 'media_player.rokkie_rollie', 'hass.attributes': {'volume_level': 0.52, 'is_volume_muted': False, 'media_content_type': 'music', 'media_duration': 71, 'media_position': 0, 'media_position_updated_at': datetime.datetime(2019, 3, 29, 11, 17, 34, 502238, tzinfo=<UTC>), 'media_title': 'Happy Birthday to You - Piano Version', 'media_artist': 'Happy Birthday', 'media_album_name': 'Happy Birthday to You', 'source_list': ['C-Dance', 'dorst', 'dorst.m4a', 'FM Brussel', 'Gozadera Fm', 'RGR FM 106.5 (Electronic and Dance)', 'RTBF Pure FM 88.8 (Top-40-Pop)', 'VRT Radio 1', 'VRT Studio Brussel', 'Where Does The Good Go'], 'shuffle': False, 'sonos_group': ['media_player.rokkie_rollie'], 'friendly_name': 'Rokkie&Rollie', 'entity_picture': '/api/media_player_proxy/media_player.rokkie_rollie?token=8a7ae8a81b0889a2833cfeeca63dd98210dbcebae9f3a728b1e3d9dbeb20d40b&cache=355c957f9c61d46b', 'supported_features': 64063}, 'hass.value': 'paused', '@timestamp': datetime.datetime(2019, 3, 29, 12, 47, 40, 729443), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.90.2', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 50.8823, 'lon': 4.7028}, 'host.architecture': 'armv7l', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}, {'index': {'_index': 'hass-events-v2-000001', '_type': 'doc', '_id': 'iXZGyWkBVxYPvKEP6fdQ', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': "failed to parse field [hass.value] of type [long] in document with id 'iXZGyWkBVxYPvKEP6fdQ'", 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'For input string: "yellow"'}}, 'data': {'hass.domain': 'sensor', 'hass.object_id': 'es_cluster_health', 'hass.entity_id': 'sensor.es_cluster_health', 'hass.attributes': {'cluster_name': 'docker-cluster', 'status': 'yellow', 'timed_out': False, 'number_of_nodes': 1, 'number_of_data_nodes': 1, 'active_primary_shards': 4, 'active_shards': 4, 'relocating_shards': 0, 'initializing_shards': 0, 'unassigned_shards': 2, 'delayed_unassigned_shards': 0, 'number_of_pending_tasks': 0, 'number_of_in_flight_fetch': 0, 'task_max_waiting_in_queue_millis': 0, 'active_shards_percent_as_number': 66.66666666666666}, 'hass.value': 'yellow', '@timestamp': datetime.datetime(2019, 3, 29, 12, 47, 40, 729443), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.90.2', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 50.8823, 'lon': 4.7028}, 'host.architecture': 'armv7l', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}])
```

**To Reproduce**
Just enabled this and restarted HA.

**Expected behavior**
No errors and zones being logged.

**Comment by legrego** [comment]
@tjorim thanks for the report -- sorry this isn't working correctly for you. Based on my testing this appears to be a compatibility issue with 7.0. I have an issue open to make this component work with 7.x (#57), so I'll add this issue to that list.

For posterity, the underlying issue appears to be with the index template/mapping. On startup on 7.0, I get the following before seeing the issue you reported:

```
Log Details (ERROR)
Fri Mar 29 2019 08:19:34 GMT-0400 (Eastern Daylight Time)
Error creating index template: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [doc : {dynamic=strict, properties={agent={properties={name={ignore_above=1024, type=keyword}, id={ignore_above=1024, type=keyword}, ephemeral_id={ignore_above=1024, type=keyword}, type={ignore_above=1024, type=keyword}, version={ignore_above=1024, type=keyword}}}, @timestamp={type=date}, ecs={properties={version={ignore_above=1024, type=keyword}}}, host={properties={geo={properties={region_iso_code={ignore_above=1024, type=keyword}, continent_name={ignore_above=1024, type=keyword}, city_name={ignore_above=1024, type=keyword}, country_iso_code={ignore_above=1024, type=keyword}, country_name={ignore_above=1024, type=keyword}, name={ignore_above=1024, type=keyword}, location={type=geo_point}, region_name={ignore_above=1024, type=keyword}}}, hostname={ignore_above=1024, type=keyword}, os={properties={kernel={ignore_above=1024, type=keyword}, name={ignore_above=1024, type=keyword}, family={ignore_above=1024, type=keyword}, version={ignore_above=1024, type=keyword}, platform={ignore_above=1024, type=keyword}, full={ignore_above=1024, type=keyword}}}, ip={type=ip}, name={ignore_above=1024, type=keyword}, id={ignore_above=1024, type=keyword}, type={ignore_above=1024, type=keyword}, user={properties={full_name={ignore_above=1024, type=keyword}, name={ignore_above=1024, type=keyword}, id={ignore_above=1024, type=keyword}, hash={ignore_above=1024, type=keyword}, email={ignore_above=1024, type=keyword}}}, mac={ignore_above=1024, type=keyword}, architecture={ignore_above=1024, type=keyword}}}, hass={type=object, properties={geo={type=object, properties={location={type=geo_point}}}, domain={ignore_above=1024, type=keyword}, attributes={dynamic=true, type=object}, entity_id={ignore_above=1024, type=keyword}, object_id={ignore_above=1024, type=keyword}, value={fields={keyword={ignore_above=2048, type=keyword}, float={ignore_malformed=true, type=float}}, type=text}}}, event={properties={severity={type=long}, original={ignore_above=1024, index=false, type=keyword, doc_values=false}, risk_score={type=float}, timezone={ignore_above=1024, type=keyword}, created={type=date}, kind={ignore_above=1024, type=keyword}, module={ignore_above=1024, type=keyword}, start={type=date}, type={ignore_above=1024, type=keyword}, duration={type=long}, risk_score_norm={type=float}, action={ignore_above=1024, type=keyword}, end={type=date}, id={ignore_above=1024, type=keyword}, category={ignore_above=1024, type=keyword}, dataset={ignore_above=1024, type=keyword}, hash={ignore_above=1024, type=keyword}, outcome={ignore_above=1024, type=keyword}}}, tags={ignore_above=1024, type=keyword}}}]')
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/elastic/__init__.py", line 432, in _create_index_template
    "all-hass-events": {}
  File "/srv/homeassistant/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/srv/homeassistant/lib/python3.5/site-packages/elasticsearch/client/indices.py", line 442, in put_template
    name), params=params, body=body)
  File "/srv/homeassistant/lib/python3.5/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/srv/homeassistant/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/srv/homeassistant/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'mapper_parsing_exception', 'Root mapping definition has unsupported parameters:  [doc : {dynamic=strict, properties={agent={properties={name={ignore_above=1024, type=keyword}, id={ignore_above=1024, type=keyword}, ephemeral_id={ignore_above=1024, type=keyword}, type={ignore_above=1024, type=keyword}, version={ignore_above=1024, type=keyword}}}, @timestamp={type=date}, ecs={properties={version={ignore_above=1024, type=keyword}}}, host={properties={geo={properties={region_iso_code={ignore_above=1024, type=keyword}, continent_name={ignore_above=1024, type=keyword}, city_name={ignore_above=1024, type=keyword}, country_iso_code={ignore_above=1024, type=keyword}, country_name={ignore_above=1024, type=keyword}, name={ignore_above=1024, type=keyword}, location={type=geo_point}, region_name={ignore_above=1024, type=keyword}}}, hostname={ignore_above=1024, type=keyword}, os={properties={kernel={ignore_above=1024, type=keyword}, name={ignore_above=1024, type=keyword}, family={ignore_above=1024, type=keyword}, version={ignore_above=1024, type=keyword}, platform={ignore_above=1024, type=keyword}, full={ignore_above=1024, type=keyword}}}, ip={type=ip}, name={ignore_above=1024, type=keyword}, id={ignore_above=1024, type=keyword}, type={ignore_above=1024, type=keyword}, user={properties={full_name={ignore_above=1024, type=keyword}, name={ignore_above=1024, type=keyword}, id={ignore_above=1024, type=keyword}, hash={ignore_above=1024, type=keyword}, email={ignore_above=1024, type=keyword}}}, mac={ignore_above=1024, type=keyword}, architecture={ignore_above=1024, type=keyword}}}, hass={type=object, properties={geo={type=object, properties={location={type=geo_point}}}, domain={ignore_above=1024, type=keyword}, attributes={dynamic=true, type=object}, entity_id={ignore_above=1024, type=keyword}, object_id={ignore_above=1024, type=keyword}, value={fields={keyword={ignore_above=2048, type=keyword}, float={ignore_malformed=true, type=float}}, type=text}}}, event={properties={severity={type=long}, original={ignore_above=1024, index=false, type=keyword, doc_values=false}, risk_score={type=float}, timezone={ignore_above=1024, type=keyword}, created={type=date}, kind={ignore_above=1024, type=keyword}, module={ignore_above=1024, type=keyword}, start={type=date}, type={ignore_above=1024, type=keyword}, duration={type=long}, risk_score_norm={type=float}, action={ignore_above=1024, type=keyword}, end={type=date}, id={ignore_above=1024, type=keyword}, category={ignore_above=1024, type=keyword}, dataset={ignore_above=1024, type=keyword}, hash={ignore_above=1024, type=keyword}, outcome={ignore_above=1024, type=keyword}}}, tags={ignore_above=1024, type=keyword}}}]')
```

**Comment by legrego** [comment]
@tjorim I opened a PR for ES7 support. If you get a chance, feel free to test it out before I merge it. I tested on my own ES6 and ES7 clusters, but the more the merrier!
https://github.com/legrego/homeassistant-elasticsearch/pull/61
