### ISSUE TITLE
failed to index - field name cannot be an empty string

### ISSUE THREAD

**Issue by kkellner** [legrego/homeassistant-elasticsearch#96]
**Environment**
Home-Assistant version: 0.108.9
Elasticsearch version: 0.2.2

Relevant `configuration.yml` settings:
```yml

elastic:
    # URL should point to your Elasticsearch cluster
    url: http://xxxxx:9200
    publish_frequency: 2
    only_publish_changed: true
    #rollover_max_age: 1d
    ilm_max_size: 50mb
    ilm_delete_after: 30d
    exclude:
      entities: [ 'sensor.es_publish_queue' ]
      domains: [ 'sun' ]
```

**Describe the bug**

Getting the following errors in log.  I'm using the Blue Iris community integration.

```
Logger: custom_components.elastic
Source: custom_components/elastic/__init__.py:512
First occurred: 1:15:23 AM (16 occurrences)
Last logged: 1:45:09 AM

Error publishing documents to Elasticsearch: ('2 document(s) failed to index.', [{'index': {'_index': 'hass-events-v4_1-000001', '_type': '_doc', '_id': 'q3NX1HEBdrLqniB6HPoW', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': 'failed to parse', 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'field name cannot be an empty string'}}, 'data': {'hass.domain': 'binary_sensor', 'hass.object_id': '172_20_0_160_alerts', 'hass.object_id_lower': '172_20_0_160_alerts', 'hass.entity_id': 'binary_sensor.172_20_0_160_alerts', 'hass.entity_id_lower': 'binary_sensor.172_20_0_160_alerts', 'hass.attributes': {'friendly_name': '172.20.0.160 Alerts', 'Motion': '172.20.0.160 Frontyard-PTZ-cam24 Motion, 172.20.0.160 frontDoor-cam12 Motion', '': '172.20.0.160 Alerts'}, 'hass.value': 1, '@timestamp': datetime.datetime(2020, 5, 2, 7, 43, 29, 756252, tzinfo=<UTC>), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.108.9', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 9999, 'lon': -9999}, 'host.architecture': 'x86_64', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}, {'index': {'_index': 'hass-events-v4_1-000001', '_type': '_doc', '_id': 'rXNX1HEBdrLqniB6HPoW', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': 'failed to parse', 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'field name cannot be an empty string'}}, 'data': {'hass.domain': 'binary_sensor', 'hass.object_id': '172_20_0_160_alerts', 'hass.object_id_lower': '172_20_0_160_alerts', 'hass.entity_id': 'binary_sensor.172_20_0_160_alerts', 'hass.entity_id_lower': 'binary_sensor.172_20_0_160_alerts', 'hass.attributes': {'friendly_name': '172.20.0.160 Alerts', 'Motion': '172.20.0.160 Frontyard-PTZ-cam24 Motion, 172.20.0.160 driveway-north-cam11 Motion, 172.20.0.160 frontDoor-cam12 Motion', '': '172.20.0.160 Alerts'}, 'hass.value': 1, '@timestamp': datetime.datetime(2020, 5, 2, 7, 43, 30, 412699, tzinfo=<UTC>), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.108.9', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 9999, 'lon': -9999}, 'host.architecture': 'x86_64', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}])
Error publishing documents to Elasticsearch: ('1 document(s) failed to index.', [{'index': {'_index': 'hass-events-v4_1-000001', '_type': '_doc', '_id': 'u3NX1HEBdrLqniB6I_r_', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': 'failed to parse', 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'field name cannot be an empty string'}}, 'data': {'hass.domain': 'binary_sensor', 'hass.object_id': '172_20_0_160_alerts', 'hass.object_id_lower': '172_20_0_160_alerts', 'hass.entity_id': 'binary_sensor.172_20_0_160_alerts', 'hass.entity_id_lower': 'binary_sensor.172_20_0_160_alerts', 'hass.attributes': {'friendly_name': '172.20.0.160 Alerts', 'Motion': '172.20.0.160 Frontyard-PTZ-cam24 Motion, 172.20.0.160 driveway-north-cam11 Motion, 172.20.0.160 frontDoor-cam12 Motion, 172.20.0.160 sideGate-cam15 Motion', '': '172.20.0.160 Alerts'}, 'hass.value': 1, '@timestamp': datetime.datetime(2020, 5, 2, 7, 43, 32, 780605, tzinfo=<UTC>), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.108.9', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 9999, 'lon': -9999}, 'host.architecture': 'x86_64', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}])
Error publishing documents to Elasticsearch: ('2 document(s) failed to index.', [{'index': {'_index': 'hass-events-v4_1-000001', '_type': '_doc', '_id': 'CHNY1HEBdrLqniB6D_7K', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': 'failed to parse', 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'field name cannot be an empty string'}}, 'data': {'hass.domain': 'binary_sensor', 'hass.object_id': '172_20_0_160_alerts', 'hass.object_id_lower': '172_20_0_160_alerts', 'hass.entity_id': 'binary_sensor.172_20_0_160_alerts', 'hass.entity_id_lower': 'binary_sensor.172_20_0_160_alerts', 'hass.attributes': {'friendly_name': '172.20.0.160 Alerts', 'Motion': '172.20.0.160 Frontyard-PTZ-cam24 Motion, 172.20.0.160 driveway-north-cam11 Motion, 172.20.0.160 sideGate-cam15 Motion', '': '172.20.0.160 Alerts'}, 'hass.value': 1, '@timestamp': datetime.datetime(2020, 5, 2, 7, 44, 32, 248915, tzinfo=<UTC>), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.108.9', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 9999, 'lon': -9999}, 'host.architecture': 'x86_64', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}, {'index': {'_index': 'hass-events-v4_1-000001', '_type': '_doc', '_id': 'CnNY1HEBdrLqniB6D_7K', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': 'failed to parse', 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'field name cannot be an empty string'}}, 'data': {'hass.domain': 'binary_sensor', 'hass.object_id': '172_20_0_160_alerts', 'hass.object_id_lower': '172_20_0_160_alerts', 'hass.entity_id': 'binary_sensor.172_20_0_160_alerts', 'hass.entity_id_lower': 'binary_sensor.172_20_0_160_alerts', 'hass.attributes': {'friendly_name': '172.20.0.160 Alerts', 'Motion': '172.20.0.160 Frontyard-PTZ-cam24 Motion, 172.20.0.160 driveway-north-cam11 Motion', '': '172.20.0.160 Alerts'}, 'hass.value': 1, '@timestamp': datetime.datetime(2020, 5, 2, 7, 44, 32, 577103, tzinfo=<UTC>), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.108.9', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 9999, 'lon': -9999}, 'host.architecture': 'x86_64', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}])
Error publishing documents to Elasticsearch: ('1 document(s) failed to index.', [{'index': {'_index': 'hass-events-v4_1-000001', '_type': '_doc', '_id': 'FnNY1HEBdrLqniB6F_61', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': 'failed to parse', 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'field name cannot be an empty string'}}, 'data': {'hass.domain': 'binary_sensor', 'hass.object_id': '172_20_0_160_alerts', 'hass.object_id_lower': '172_20_0_160_alerts', 'hass.entity_id': 'binary_sensor.172_20_0_160_alerts', 'hass.entity_id_lower': 'binary_sensor.172_20_0_160_alerts', 'hass.attributes': {'friendly_name': '172.20.0.160 Alerts', 'Motion': '172.20.0.160 driveway-north-cam11 Motion', '': '172.20.0.160 Alerts'}, 'hass.value': 1, '@timestamp': datetime.datetime(2020, 5, 2, 7, 44, 33, 739323, tzinfo=<UTC>), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.108.9', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 9999, 'lon': -9999}, 'host.architecture': 'x86_64', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}])
Error publishing documents to Elasticsearch: ('1 document(s) failed to index.', [{'index': {'_index': 'hass-events-v4_1-000001', '_type': '_doc', '_id': '0nNY1HEBdrLqniB6nf9t', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': 'failed to parse', 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'field name cannot be an empty string'}}, 'data': {'hass.domain': 'binary_sensor', 'hass.object_id': '172_20_0_160_alerts', 'hass.object_id_lower': '172_20_0_160_alerts', 'hass.entity_id': 'binary_sensor.172_20_0_160_alerts', 'hass.entity_id_lower': 'binary_sensor.172_20_0_160_alerts', 'hass.attributes': {'friendly_name': '172.20.0.160 Alerts', '': '172.20.0.160 Alerts'}, 'hass.value': 1, '@timestamp': datetime.datetime(2020, 5, 2, 7, 45, 8, 150655, tzinfo=<UTC>), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.108.9', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 9999, 'lon': -9999}, 'host.architecture': 'x86_64', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}])
Traceback (most recent call last):
  File "/config/custom_components/elastic/__init__.py", line 512, in do_publish
    bulk_response = bulk(self._gateway.get_client(), actions)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/__init__.py", line 192, in streaming_bulk
    raise_on_error, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/__init__.py", line 137, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
elasticsearch.helpers.BulkIndexError: ('1 document(s) failed to index.'
```

**To Reproduce**

Install Blue Iris community integration (version d2ba3fc)
Install Elastic Search community integration.

**Comment by legrego** [comment]
Hey @kkellner, thanks for the bug report. Did you happen to see this on any earlier versions of this component, or is `0.2.2` the first version that you tried?

**Comment by legrego** [comment]
Followup question: Can you provide the full set of attributes from the `binary_sensor.172_20_0_160_alerts` sensor? I'm curious to see which attribute we're mangling into an empty string.

It appears to be the same value as `friendly_name`, but I'm not sure where it's coming from:
> '': '172.20.0.160 Alerts'

**Comment by kkellner** [comment]
I think the issue is with the latest version of Blue Iris integration.....   It seems to have created a bunch of invalid / unavailable sensors.  Here is what its showing:

![image](https://user-images.githubusercontent.com/9540241/80896497-2a4a5700-8cac-11ea-925b-bd84fc92feee.png)

I rolled back to an older version of the Blue Iris integration and it seems to be working.   I'll leave this issue open for a bit until I can confirm.

**Comment by kkellner** [comment]
Still occurring with older version of Blue Iris integration, but looking at the attributes, it does seem like the key is missing.   The UI shows: `: BlueIris Alerts`.    Once a stable version of Blue Iris is released, if the problem continues, I'll open an issue on the Blue Iris integration about the missing key in the attribute.

```
Error publishing documents to Elasticsearch: ('1 document(s) failed to index.', [{'index': {'_index': 'hass-events-v4_1-000001', '_type': '_doc', '_id': 'eYE72HEBdrLqniB6KSmU', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': 'failed to parse', 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'field name cannot be an empty string'}}, 'data': {'hass.domain': 'binary_sensor', 'hass.object_id': 'blueiris_alerts', 'hass.object_id_lower': 'blueiris_alerts', 'hass.entity_id': 'binary_sensor.blueiris_alerts', 'hass.entity_id_lower': 'binary_sensor.blueiris_alerts', 'hass.attributes': {'friendly_name': 'BlueIris Alerts', 'Motion': 'BlueIris back-porch-cam7 Motion', '': 'BlueIris Alerts'}, 'hass.value': 1, '@timestamp': datetime.datetime(2020, 5, 3, 1, 51, 28, 30219, tzinfo=<UTC>), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.108.9', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 9999, 'lon': -9999}, 'host.architecture': 'x86_64', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}])
Error publishing documents to Elasticsearch: ('1 document(s) failed to index.', [{'index': {'_index': 'hass-events-v4_1-000001', '_type': '_doc', '_id': 'KoE72HEBdrLqniB6tivx', 'status': 400, 'error': {'type': 'mapper_parsing_exception', 'reason': 'failed to parse', 'caused_by': {'type': 'illegal_argument_exception', 'reason': 'field name cannot be an empty string'}}, 'data': {'hass.domain': 'binary_sensor', 'hass.object_id': 'blueiris_alerts', 'hass.object_id_lower': 'blueiris_alerts', 'hass.entity_id': 'binary_sensor.blueiris_alerts', 'hass.entity_id_lower': 'binary_sensor.blueiris_alerts', 'hass.attributes': {'friendly_name': 'BlueIris Alerts', '': 'BlueIris Alerts'}, 'hass.value': 1, '@timestamp': datetime.datetime(2020, 5, 3, 1, 52, 4, 215443, tzinfo=<UTC>), 'agent.name': 'My Home Assistant', 'agent.type': 'hass', 'agent.version': '0.108.9', 'ecs.version': '1.0.0', 'host.geo.location': {'lat': 9999, 'lon': -9999}, 'host.architecture': 'x86_64', 'host.os.name': 'Linux', 'host.hostname': 'homeassistant', 'tags': ['hass']}}}])
```

![image](https://user-images.githubusercontent.com/9540241/80896857-17d21c80-8cb0-11ea-9414-dccd5e0501f7.png)

**Comment by legrego** [comment]
Good to know it’s a bug on the Blue Iris side, thanks for taking the time to research this for me.

Nevertheless, We can make this component more resilient to bad data by simply skipping these invalid attributes.

**Comment by kkellner** [comment]
I agree on making it more resilient to bad data.  However, maybe to help track down bad data, would it be possible to change an empty key to something like "INVALID_KEY" and keep the value.  This might be helpful for integration authors to know they have invalid data.

**Comment by legrego** [comment]
> I agree on making it more resilient to bad data.  However, maybe to help track down bad data, would it be possible to change an empty key to something like "INVALID_KEY" and keep the value.  This might be helpful for integration authors to know they have invalid data.

Yeah that’s certainly doable too. I’m not opposed to that approach
